services:



  edge_ingestion_service:
    build: ./edge_ingestion_service
    image: vesudarsanCloud/edge_ingestion_service:1.0.0
    container_name: edge_ingestion_service
      
    ports:
      - "6001:6001" 

    volumes:
     - D:/cloudCompute/config.json:/app/config/config.json:ro
     - D:/cloudCompute:/app/data
    
    environment:
      - PYTHONUNBUFFERED=1
      - CONTAINER_NAME=edge_ingestion_service
    
    restart: unless-stopped
    networks:
      - cloudcompute-net

#   rabbitmq:
#     image: rabbitmq:3.11-management
#     hostname: rabbit
#     environment:
#       RABBITMQ_DEFAULT_USER: user
#       RABBITMQ_DEFAULT_PASS: password
#       # Enable MQTT plugin at startup
#       RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_plugins_enable mqtt,rabbitmq_management"
#     ports:
#       - "5672:5672"     # AMQP
#       - "15672:15672"   # Management UI
#       - "1883:1883"     # MQTT plain
#       - "8883:8883"     # MQTT over TLS (if you enable it)
#     volumes:
#       - rabbitmq-data:/var/lib/rabbitmq
# volumes:
#   rabbitmq-data:


#   influxdb:
#     image: influxdb:2.7
#     container_name: influxdb
#     ports:
#       - "8086:8086"
#     volumes:
#       - influxdb-data:/var/lib/influxdb2
#     environment:
#       - DOCKER_INFLUXDB_INIT_MODE=setup
#       - DOCKER_INFLUXDB_INIT_USERNAME=admin
#       - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
#       - DOCKER_INFLUXDB_INIT_ORG=drone-org
#       - DOCKER_INFLUXDB_INIT_BUCKET=drone_telemetry
#       - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=drone-secret-token
#     restart: unless-stopped

# volumes:
#   influxdb-data:

networks:
  cloudcompute-net:
    driver: bridge